# nombre del pipeline
name: GH-build-on-server-DEV

# eventos disparadores 
on:
  push:
    branches: [ "main" ] # eventos disparadores en branch main

jobs:
  build:

    runs-on: ubuntu-24.04 # siempre explicitar la version del Sistema Operativo

    steps:    
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}          
          port: ${{ secrets.SERVER_PORT }}
          script: cd pipelines && dotnet build && cd Aplicacion && dotnet publish -c Release -o ./publish
